package ir.hadipoor.eviltower.ui

import androidx.compose.runtime.Composable
import androidx.compose.runtime.ProvidableCompositionLocal
import androidx.compose.runtime.compositionLocalOf

/**
 * All user-facing text of the game.
 *
 * Persian ([Fa]) is the default and the language the game is designed around; English ([En]) is an
 * optional toggle in the settings screen. Keeping the strings in one Kotlin object (instead of
 * `strings.xml`) lets the player switch language instantly without recreating the activity.
 */
data class GameStrings(
    val isRtl: Boolean,
    val appName: String,
    val tagline: String,
    val loading: String,
    // main menu
    val newGame: String,
    val continueClimb: String,
    val shop: String,
    val achievements: String,
    val settings: String,
    val leaderboard: String,
    val exit: String,
    val story: String,
    // hud
    val floor: String,
    val coins: String,
    val gems: String,
    val score: String,
    val best: String,
    val pause: String,
    // pause
    val paused: String,
    val resume: String,
    val restart: String,
    val exitToMenu: String,
    // game over
    val gameOver: String,
    val gameOverSub: String,
    val floorsClimbed: String,
    val coinsEarned: String,
    val newRecord: String,
    val tryAgain: String,
    val mainMenu: String,
    val watchAdContinue: String,
    val doubleCoins: String,
    val victory: String,
    val victorySub: String,
    // shop
    val heroSkins: String,
    val towerThemes: String,
    val upgrades: String,
    val buy: String,
    val owned: String,
    val equipped: String,
    val equip: String,
    val notEnoughCoins: String,
    val notEnoughGems: String,
    val level: String,
    val maxLevel: String,
    val buyGems: String,
    val removeAds: String,
    // settings
    val musicVolume: String,
    val soundVolume: String,
    val controlScheme: String,
    val controlSwipe: String,
    val controlButtons: String,
    val controlTilt: String,
    val vibration: String,
    val language: String,
    val persian: String,
    val english: String,
    val resetProgress: String,
    val resetProgressConfirm: String,
    val cancel: String,
    val confirm: String,
    val on: String,
    val off: String,
    val about: String,
    val aboutText: String,
    // achievements
    val locked: String,
    val unlocked: String,
    val progress: String,
    // leaderboard
    val bestScore: String,
    val bestFloor: String,
    val totalCoins: String,
    val totalRuns: String,
    val enemiesDefeated: String,
    val localScoresNote: String,
    val noScores: String,
    val rank: String,
    // misc
    val back: String,
    val tapToStart: String,
    val readyGo: String,
    val bossWarning: String,
    val gateLocked: String,
    val controlsReversed: String,
) {
    companion object {
        val Fa = GameStrings(
            isRtl = true,
            appName = "برج شیطانی",
            tagline = "هر شب یک طبقه بلندتر، هر شب یک روح بیشتر",
            loading = "در حال باز کردن دروازه...",
            newGame = "شروع صعود",
            continueClimb = "ادامه صعود",
            shop = "فروشگاه",
            achievements = "دستاوردها",
            settings = "تنظیمات",
            leaderboard = "امتیازات برتر",
            exit = "خروج",
            story = "در دل پادشاهی ویران، برجی نفرین‌شده سر برآورده است. هر شب یک طبقه بلندتر می‌شود " +
                "و روحی تازه را به درون می‌کشد. تو آخرین اسیر این برجی؛ طبقه به طبقه بالا برو، " +
                "از تله‌ها و هیولاها بگذر، یادگارهای باستانی را بردار و ارباب برج را شکست بده... " +
                "یا برای همیشه در تاریکی بمان.",
            floor = "طبقه",
            coins = "سکه",
            gems = "جواهر",
            score = "امتیاز",
            best = "رکورد",
            pause = "توقف",
            paused = "بازی متوقف شد",
            resume = "ادامه",
            restart = "شروع دوباره",
            exitToMenu = "خروج به منو",
            gameOver = "سقوط کردی!",
            gameOverSub = "برج تو را به طبقه‌ی اول بازگرداند",
            floorsClimbed = "طبقات پیموده‌شده",
            coinsEarned = "سکه‌های به‌دست‌آمده",
            newRecord = "رکورد تازه!",
            tryAgain = "دوباره تلاش کن",
            mainMenu = "منوی اصلی",
            watchAdContinue = "تماشای ویدیو و ادامه از همین طبقه",
            doubleCoins = "دو برابر کردن سکه‌ها با تماشای ویدیو",
            victory = "ارباب برج شکست خورد!",
            victorySub = "نفرین برج پایان یافت و تو آزاد شدی",
            heroSkins = "پوسته‌ی قهرمان",
            towerThemes = "پوسته‌ی برج",
            upgrades = "ارتقاهای دائمی",
            buy = "خرید",
            owned = "خریداری‌شده",
            equipped = "فعال",
            equip = "انتخاب",
            notEnoughCoins = "سکه کافی نداری",
            notEnoughGems = "جواهر کافی نداری",
            level = "سطح",
            maxLevel = "بیشینه",
            buyGems = "خرید بسته جواهر",
            removeAds = "حذف تبلیغات",
            musicVolume = "صدای موسیقی",
            soundVolume = "صدای جلوه‌ها",
            controlScheme = "شیوه کنترل",
            controlSwipe = "کشیدن انگشت",
            controlButtons = "دکمه‌های روی صفحه",
            controlTilt = "حرکت با شیب گوشی",
            vibration = "لرزش",
            language = "زبان",
            persian = "فارسی",
            english = "English",
            resetProgress = "پاک کردن پیشرفت",
            resetProgressConfirm = "همه‌ی سکه‌ها، رکوردها و پوسته‌ها پاک شوند؟",
            cancel = "انصراف",
            confirm = "تایید",
            on = "روشن",
            off = "خاموش",
            about = "درباره بازی",
            aboutText = "برج شیطانی — بازی صعود از برج نفرین‌شده. ساخته‌شده با Kotlin و Jetpack Compose، " +
                "با گرافیک کاملاً برداری و متحرک. نسخه ۱.۰.۰",
            locked = "قفل",
            unlocked = "باز شد",
            progress = "پیشرفت",
            bestScore = "بهترین امتیاز",
            bestFloor = "بلندترین طبقه",
            totalCoins = "مجموع سکه‌ها",
            totalRuns = "تعداد صعودها",
            enemiesDefeated = "دشمنان شکست‌خورده",
            localScoresNote = "امتیازها روی همین دستگاه ذخیره می‌شوند؛ نیازی به حساب کاربری نیست.",
            noScores = "هنوز صعودی ثبت نشده است",
            rank = "رتبه",
            back = "بازگشت",
            tapToStart = "برای شروع لمس کن",
            readyGo = "برو!",
            bossWarning = "نگهبان طبقه بیدار شد!",
            gateLocked = "تا نگهبان را شکست ندهی، دروازه باز نمی‌شود",
            controlsReversed = "گاز خواب‌آور! کنترل‌ها معکوس شد",
        )

        val En = GameStrings(
            isRtl = false,
            appName = "Evil Tower",
            tagline = "Every night one floor taller, one soul heavier",
            loading = "Opening the gate...",
            newGame = "Start Climb",
            continueClimb = "Continue Climb",
            shop = "Shop",
            achievements = "Achievements",
            settings = "Settings",
            leaderboard = "High Scores",
            exit = "Exit",
            story = "A cursed tower has risen in a ruined kingdom. Every night it grows taller and " +
                "pulls in a new soul. Climb floor by floor, dodge the traps and monsters, collect " +
                "ancient relics and defeat the Lord of the Tower — or stay in the dark forever.",
            floor = "Floor",
            coins = "Coins",
            gems = "Gems",
            score = "Score",
            best = "Best",
            pause = "Pause",
            paused = "Paused",
            resume = "Resume",
            restart = "Restart",
            exitToMenu = "Exit to Menu",
            gameOver = "You fell!",
            gameOverSub = "The tower sent you back to the ground floor",
            floorsClimbed = "Floors climbed",
            coinsEarned = "Coins earned",
            newRecord = "New record!",
            tryAgain = "Try Again",
            mainMenu = "Main Menu",
            watchAdContinue = "Watch a video and continue from this floor",
            doubleCoins = "Double your coins with a video",
            victory = "The Lord of the Tower has fallen!",
            victorySub = "The curse is broken and you are free",
            heroSkins = "Hero skins",
            towerThemes = "Tower themes",
            upgrades = "Permanent upgrades",
            buy = "Buy",
            owned = "Owned",
            equipped = "Equipped",
            equip = "Equip",
            notEnoughCoins = "Not enough coins",
            notEnoughGems = "Not enough gems",
            level = "Level",
            maxLevel = "Max",
            buyGems = "Buy gem pack",
            removeAds = "Remove ads",
            musicVolume = "Music volume",
            soundVolume = "Sound volume",
            controlScheme = "Control scheme",
            controlSwipe = "Swipe",
            controlButtons = "On-screen buttons",
            controlTilt = "Tilt",
            vibration = "Vibration",
            language = "Language",
            persian = "فارسی",
            english = "English",
            resetProgress = "Reset progress",
            resetProgressConfirm = "Erase all coins, records and skins?",
            cancel = "Cancel",
            confirm = "Confirm",
            on = "On",
            off = "Off",
            about = "About",
            aboutText = "Evil Tower — climb the cursed tower. Built with Kotlin and Jetpack Compose, " +
                "fully animated vector art. Version 1.0.0",
            locked = "Locked",
            unlocked = "Unlocked",
            progress = "Progress",
            bestScore = "Best score",
            bestFloor = "Highest floor",
            totalCoins = "Total coins",
            totalRuns = "Runs",
            enemiesDefeated = "Enemies defeated",
            localScoresNote = "Scores are stored on this device — no account needed.",
            noScores = "No climb recorded yet",
            rank = "Rank",
            back = "Back",
            tapToStart = "Tap to start",
            readyGo = "Go!",
            bossWarning = "The floor guardian awakens!",
            gateLocked = "The gate stays shut until the guardian falls",
            controlsReversed = "Sleeping gas! Controls reversed",
        )

        fun of(language: String): GameStrings = if (language == "en") En else Fa
    }
}

val LocalStrings: ProvidableCompositionLocal<GameStrings> = compositionLocalOf { GameStrings.Fa }

/** Shorthand for `LocalStrings.current` inside composables. */
val strings: GameStrings
    @Composable get() = LocalStrings.current
