package ir.hadipoor.eviltower.game.render

import androidx.compose.ui.geometry.Offset
import androidx.compose.ui.graphics.Color
import androidx.compose.ui.graphics.Path
import androidx.compose.ui.graphics.drawscope.DrawScope
import androidx.compose.ui.graphics.drawscope.DrawStyle
import androidx.compose.ui.graphics.drawscope.Fill
import androidx.compose.ui.graphics.drawscope.withTransform
import androidx.compose.ui.graphics.vector.PathParser

/**
 * ## The SVG pipeline of برج شیطانی
 *
 * Every sprite in the game is authored as **SVG path data** inside a `100 x 100` view-box
 * (see [SvgPaths]). The identical `d=` strings are mirrored as real `.svg` files under
 * `app/src/main/assets/svg/` (generated by `tools/export_svg.py`) so designers can open, edit and
 * re-export them with any vector tool.
 *
 * At runtime the path strings are parsed **once** by [PathParser] into Compose [Path] objects and
 * cached in [SpriteCache]. Nothing is re-parsed per frame — the game loop only pushes transform
 * matrices, which keeps the renderer at 60fps even with dozens of animated sprites on screen.
 *
 * ### Adding a new sprite
 * 1. add the path data as a `const val` inside [SvgPaths];
 * 2. run `python3 tools/export_svg.py` to export the matching `.svg` file;
 * 3. draw it with [drawSvg] from any renderer function.
 */
object SpriteCache {
    private val cache = HashMap<String, Path>(96)

    fun path(pathData: String): Path = cache.getOrPut(pathData) {
        PathParser().parsePathString(pathData).toPath()
    }

    fun clear() = cache.clear()
}

/**
 * Draws a cached SVG path inside the destination rectangle (screen pixels).
 *
 * @param pivotX/@param pivotY rotation pivot in 0..1 of the destination rect.
 */
fun DrawScope.drawSvg(
    pathData: String,
    x: Float,
    y: Float,
    w: Float,
    h: Float,
    color: Color,
    alpha: Float = 1f,
    rotation: Float = 0f,
    pivotX: Float = 0.5f,
    pivotY: Float = 0.5f,
    flipX: Boolean = false,
    style: DrawStyle = Fill,
) {
    if (w <= 0f || h <= 0f || alpha <= 0.001f) return
    val path = SpriteCache.path(pathData)
    withTransform({
        translate(x, y)
        if (rotation != 0f) rotate(rotation, Offset(w * pivotX, h * pivotY))
        scale(w / 100f, h / 100f, Offset.Zero)
        if (flipX) scale(-1f, 1f, Offset(50f, 50f))
    }) {
        drawPath(path, color, alpha = alpha, style = style)
    }
}

/**
 * All vector art of the game, as SVG path data in a 100x100 view-box.
 *
 * Naming convention: `<SUBJECT>_<PART>` — e.g. `HERO_TORSO`, `BAT_WING`, `TRAP_BLADE`.
 * Sprites are authored facing **right**; the renderer mirrors them with `flipX`.
 */
object SvgPaths {

    // --- Hero: شوالیه گرفتار (the trapped knight) -----------------------------------------
    const val HERO_CAPE =
        "M34,26 C22,42 20,64 26,82 L44,72 L46,30 Z"
    const val HERO_TORSO =
        "M34,26 L66,26 C68,44 66,58 62,70 L38,70 C34,58 32,44 34,26 Z"
    const val HERO_BELT =
        "M36,62 L64,62 L63,70 L37,70 Z"
    const val HERO_HEAD =
        "M32,10 C32,-1 68,-1 68,10 L68,26 C68,34 32,34 32,26 Z"
    const val HERO_HELMET_CREST =
        "M46,-4 L54,-4 L58,10 L42,10 Z"
    const val HERO_VISOR =
        "M36,14 L64,14 L64,20 L36,20 Z"
    const val HERO_LIMB =
        "M0,0 L100,0 L100,100 L0,100 Z"
    const val HERO_SWORD =
        "M40,0 L60,0 L60,66 L50,80 L40,66 Z"
    const val HERO_SWORD_HILT =
        "M18,62 L82,62 L82,74 L18,74 Z"

    // --- مار سنگی (Stone Serpent) ----------------------------------------------------------
    const val SERPENT_BODY =
        "M4,66 C18,40 30,86 46,60 C60,38 74,80 96,52 L96,78 C74,96 60,66 46,84 C30,100 18,66 4,86 Z"
    const val SERPENT_HEAD =
        "M74,34 C90,28 100,40 98,54 C96,66 82,70 74,62 Z"
    const val SERPENT_EYE =
        "M86,42 C90,40 94,44 92,49 C90,53 84,52 84,47 Z"

    // --- خفاش شیطانی (Evil Bat) -------------------------------------------------------------
    const val BAT_BODY =
        "M38,34 C50,26 62,32 64,46 C66,62 54,74 50,74 C46,74 34,62 36,46 Z"
    const val BAT_WING =
        "M50,38 C34,20 12,20 2,36 C14,34 18,40 14,48 C26,44 34,50 36,58 Z"
    const val BAT_EAR =
        "M42,30 L36,10 L52,24 Z"
    const val BAT_EYE =
        "M42,44 C46,42 50,44 50,48 C50,52 44,54 42,50 Z"

    // --- اسکلت جنگجو (Skeleton Warrior) ------------------------------------------------------
    const val SKELETON_SKULL =
        "M32,8 C32,-2 68,-2 68,10 L68,26 C68,36 58,40 50,40 C42,40 32,36 32,26 Z"
    const val SKELETON_JAW =
        "M38,36 L62,36 L60,46 L40,46 Z"
    const val SKELETON_RIBS =
        "M40,46 L60,46 L58,78 L42,78 Z M34,52 L66,52 L66,56 L34,56 Z M35,62 L65,62 L65,66 L35,66 Z"
    const val SKELETON_BONE =
        "M0,0 L100,0 L100,100 L0,100 Z"
    const val SKELETON_AXE =
        "M30,4 C58,-4 78,10 76,30 L58,26 C58,16 46,12 34,18 Z"

    // --- گرگ سایه (Shadow Wolf) --------------------------------------------------------------
    const val WOLF_BODY =
        "M8,56 C16,36 36,30 56,34 C70,36 84,30 92,20 L94,44 C92,58 78,70 58,72 L20,72 C10,70 4,64 8,56 Z"
    const val WOLF_HEAD =
        "M66,26 L78,6 L84,26 L96,14 L98,34 C98,46 84,52 74,48 C66,44 62,34 66,26 Z"
    const val WOLF_TAIL =
        "M8,44 C-6,38 -4,20 8,14 C6,28 14,36 22,40 Z"
    const val WOLF_EYE =
        "M78,26 C84,24 88,28 86,33 C84,37 76,36 76,31 Z"

    // --- دیو دروازه‌بان (Gate Guardian, mini-boss) ----------------------------------------------
    const val GUARDIAN_BODY =
        "M22,30 C22,14 78,14 78,30 L86,74 C86,90 14,90 14,74 Z"
    const val GUARDIAN_HORN =
        "M18,26 C6,14 10,2 22,0 C18,10 26,18 32,22 Z M82,26 C94,14 90,2 78,0 C82,10 74,18 68,22 Z"
    const val GUARDIAN_EYE =
        "M32,36 C40,32 48,38 44,46 C40,52 28,48 30,40 Z M68,36 C60,32 52,38 56,46 C60,52 72,48 70,40 Z"
    const val GUARDIAN_MOUTH =
        "M34,58 L66,58 L62,70 L38,70 Z M40,58 L44,66 L48,58 Z M52,58 L56,66 L60,58 Z"
    const val GUARDIAN_ARM =
        "M0,0 L100,0 L100,100 L0,100 Z"

    // --- ارباب برج (Lord of the Tower, boss) ---------------------------------------------------
    const val LORD_ROBE =
        "M50,6 C74,6 86,28 88,58 L96,96 L4,96 L12,58 C14,28 26,6 50,6 Z"
    const val LORD_HOOD =
        "M50,2 C70,2 80,18 78,34 C70,26 60,22 50,22 C40,22 30,26 22,34 C20,18 30,2 50,2 Z"
    const val LORD_FACE =
        "M34,26 C42,20 58,20 66,26 C64,42 56,50 50,50 C44,50 36,42 34,26 Z"
    const val LORD_EYE =
        "M40,30 C45,28 49,32 47,37 C45,41 38,40 38,35 Z M60,30 C55,28 51,32 53,37 C55,41 62,40 62,35 Z"
    const val LORD_STAFF =
        "M46,0 L54,0 L54,100 L46,100 Z"
    const val LORD_ORB =
        "M50,4 C70,4 82,20 82,38 C82,58 68,72 50,72 C32,72 18,58 18,38 C18,20 30,4 50,4 Z"

    // --- تله‌ها (Traps) --------------------------------------------------------------------------
    const val TRAP_BLADE =
        "M50,2 L60,32 L92,22 L70,48 L98,66 L64,66 L66,98 L46,72 L22,94 L30,62 L2,54 L34,40 L20,10 L48,28 Z"
    const val TRAP_BLADE_CORE =
        "M50,34 C60,34 68,42 68,52 C68,62 60,70 50,70 C40,70 32,62 32,52 C32,42 40,34 50,34 Z"
    const val TRAP_FIRE =
        "M50,2 C58,26 78,34 74,60 C72,82 60,98 50,98 C40,98 26,84 26,60 C26,38 44,28 50,2 Z"
    const val TRAP_FIRE_CORE =
        "M50,34 C56,50 64,56 62,70 C60,84 54,92 50,92 C46,92 38,84 38,70 C38,56 46,50 50,34 Z"
    const val TRAP_SPIKE =
        "M0,100 L14,20 L28,100 Z M30,100 L44,10 L58,100 Z M60,100 L74,20 L88,100 Z"
    const val TRAP_CRUSHER =
        "M2,0 L98,0 L98,64 L74,100 L26,100 L2,64 Z"
    const val TRAP_GAS =
        "M22,68 C6,68 4,46 20,42 C20,22 46,16 56,30 C74,22 92,38 84,56 C94,66 86,84 70,80 C58,92 32,88 22,68 Z"

    // --- آیتم‌ها (Pickups) ----------------------------------------------------------------------
    const val COIN_BODY =
        "M50,2 C76,2 98,24 98,50 C98,76 76,98 50,98 C24,98 2,76 2,50 C2,24 24,2 50,2 Z"
    const val COIN_INNER =
        "M50,14 C70,14 86,30 86,50 C86,70 70,86 50,86 C30,86 14,70 14,50 C14,30 30,14 50,14 Z"
    const val COIN_MARK =
        "M42,28 L58,28 L58,44 L70,44 L70,58 L58,58 L58,74 L42,74 L42,58 L30,58 L30,44 L42,44 Z"
    const val GEM_BODY =
        "M50,2 L92,34 L74,96 L26,96 L8,34 Z"
    const val GEM_FACET =
        "M50,2 L74,96 L26,96 Z"
    const val HEART_BODY =
        "M50,92 C10,64 4,40 18,24 C32,8 50,20 50,34 C50,20 68,8 82,24 C96,40 90,64 50,92 Z"
    const val SHIELD_BODY =
        "M50,2 L92,18 C92,58 76,86 50,98 C24,86 8,58 8,18 Z"
    const val SHIELD_INNER =
        "M50,16 L80,28 C80,56 68,76 50,86 C32,76 20,56 20,28 Z"
    const val WINGS_BODY =
        "M50,40 C34,14 10,10 2,30 C16,30 20,40 16,52 C30,46 42,52 46,62 Z " +
            "M50,40 C66,14 90,10 98,30 C84,30 80,40 84,52 C70,46 58,52 54,62 Z"
    const val SPEED_BOLT =
        "M58,2 L26,54 L48,54 L38,98 L76,40 L52,40 Z"
    const val MAGNET_BODY =
        "M18,92 L18,44 C18,20 82,20 82,44 L82,92 L60,92 L60,44 C60,34 40,34 40,44 L40,92 Z"
    const val MAGNET_TIP =
        "M18,92 L40,92 L40,74 L18,74 Z M60,92 L82,92 L82,74 L60,74 Z"

    // --- محیط (Environment) ---------------------------------------------------------------------
    const val BRICK =
        "M2,2 L98,2 L98,98 L2,98 Z"
    const val TORCH_HOLDER =
        "M40,54 L60,54 L56,98 L44,98 Z M34,44 L66,44 L66,56 L34,56 Z"
    const val TORCH_FLAME =
        "M50,0 C58,20 74,28 70,48 C68,66 58,78 50,78 C42,78 32,66 32,48 C32,30 44,22 50,0 Z"
    const val FOG_BLOB =
        "M10,60 C0,44 16,28 32,34 C40,16 70,14 78,34 C96,32 104,54 88,64 C74,80 22,80 10,60 Z"
    const val GATE_ARCH =
        "M14,100 L14,40 C14,12 86,12 86,40 L86,100 L66,100 L66,44 C66,28 34,28 34,44 L34,100 Z"
    const val TOWER_LOGO =
        "M50,2 L78,34 L70,34 L70,44 L62,44 L62,34 L56,34 L56,44 L44,44 L44,34 L38,34 L38,44 L30,44 " +
            "L30,34 L22,34 Z M30,44 L70,44 L70,98 L30,98 Z"
    const val SKULL_MARK =
        "M50,6 C74,6 90,24 90,46 C90,60 82,70 74,76 L74,94 L26,94 L26,76 C18,70 10,60 10,46 " +
            "C10,24 26,6 50,6 Z"
}
